export enum DispatchType {
	WELCOME = 'WELCOME',
	REQUEST_AUTH = 'REQUEST_AUTH',
	AUTH_RESPONSE = 'AUTH_RESPONSE',
	REQUEST_DATA = 'REQUEST_DATA',
	DATA_UPDATE = 'DATA_UPDATE',
	REQUEST_IMAGE = 'REQUEST_IMAGE',
	IMAGE_RESPONSE = 'IMAGE_RESPONSE',
	REQUEST_VIDEO = 'REQUEST_VIDEO',
	VIDEO_RESPONSE = 'VIDEO_RESPONSE',
	REQUEST_REPLY = 'REQUEST_REPLY',
	REPLY_RESPONSE = 'REPLY_RESPONSE'
}
